name: '🚀 Tag & Release on ODC'
resources:
  repositories:
    - repository: cordova-outsystems-inappbrowser
      type: github
      name: OutSystems/cordova-outsystems-inappbrowser
      endpoint: OutSystems
    - repository: MobilePluginsODCPipeline
      type: github
      ref: feat/add-publishing-process
      name: OutSystems/MobilePluginsODCPipeline
      endpoint: OutSystems

trigger: none

pool:
  vmImage: ubuntu-20.04
variables:
  - name: StampsInformationFileName
    value: eng-mobile.StampsInformation.json
  - name: PLUGIN_APP_KEY
    value: b0c15cc5-6fbd-4d67-8889-f7dcf0329a28
  - group: MobileConfigCredentials
  - group: ModelAPI_InternalCode

parameters:
  - name: pluginURL
    type: string
  - name: forgeVersion
    type: string
  - name: mabs
    type: string
  - name: releaseNotes
    type: string

stages:
  - stage: UpdateWrapper
    displayName: '✍🏻 Update Plugin Extensibility Configurations'
    jobs:
      - job: UpdateWrapper
        displayName: Update Wrapper's Javascript
        steps:
          - checkout: self
          - checkout: MobilePluginsODCPipeline
          - template: build/ci/update-wrapper.yaml@MobilePluginsODCPipeline
            parameters:
              secretFileName: $(StampsInformationFileName)
              scriptToRun: UpdateExtensibilityOnPluginWrapper
              PLUGIN_APP_KEY: $(PLUGIN_APP_KEY)
              PLUGIN_UPDATE_URL: ${{ parameters.pluginURL }}
              PLUGIN_UPDATE_VERSION: ${{ parameters.forgeVersion }}
              workingDirectory: $(System.DefaultWorkingDirectory)/MobilePluginsODCPipeline

  - stage: Release
    displayName: 🚀 Release on Tenant
    jobs:
      - job: Release
        displayName: Publish Updated OML
        steps:
          - checkout: self
          - checkout: MobilePluginsODCPipeline
          - template: build/ci/tag-plugin.yaml@MobilePluginsODCPipeline
            parameters:
              secretFileName: $(StampsInformationFileName)
              pluginKey: $(PLUGIN_APP_KEY)
              forgeVersion: ${{ parameters.forgeVersion }}
              releaseNotes: ${{ parameters.releaseNotes }}
              workingDirectory: $(System.DefaultWorkingDirectory)/MobilePluginsODCPipeline
